//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_SmartPhone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Showonhome { get; set; }
    }
}
